name: Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG_LATEST: ${{ secrets.DOCKER_USERNAME }}/image-react-app:latest
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DEPLOY_HOSTNAME: ${{ secrets.DEPLOY_HOSTNAME }}
  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_TAG_LATEST .
          docker push $IMAGE_TAG_LATEST

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to remote server
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $DEPLOY_HOSTNAME  >> ~/.ssh/known_hosts
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh $DEPLOY_USER@$DEPLOY_HOSTNAME "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker pull $IMAGE_TAG_LATEST && docker container rm -f react-app-ntv || true && docker run -d -p 3016:3000 --name react-app-ntv $IMAGE_TAG_LATEST"
