name: Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG_LATEST: ${{ secrets.DOCKER_USERNAME }}/image:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_TAG_LATEST .
          docker push $IMAGE_TAG_LATEST

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOSTNAME }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull $IMAGE_TAG_LATEST
            docker container rm -f react-app-ntv || true
            docker run -d -p 3016:3000 --name react-app-ntv $IMAGE_TAG_LATEST
